[package]
name = "pache"
version = "0.0.1"
license = "BSD-3"
authors = ["Yokodake <yokodake@cinnabar.fr"]
description = "std-like library for remilia"
repository = "https://github.com/yokodake/remilia"
edition = "2018"

[dependencies]
spin = "*"