[unstable]
build-std-features = ["compiler-builtins-mem"] # FIXME
build-std = ["core", "compiler_builtins"]

[build]
target = ".cargo/x86_64-osdev-target.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
